[font]
normal.family = "FantasqueSansM Nerd Font"
bold.family = "FantasqueSansM Nerd Font"
italic.family = "FantasqueSansM Nerd Font"
size = 11.0

[general]
import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

